### ISSUE TITLE
Lower bound is higher than upper bound?

### ISSUE THREAD

**Issue by poliquin** [poliquin/io273#1]
Estimated bounds for CDF in 1(2) appear to be reversed, but the code seems to follow what's in the Haile & Tamer (2003) paper.  The plot currently treats the estimated lower bound as an upper bound, and the estimated upper bound as a lower bound since it's possible I simply reversed the two calculations.

**Comment by dhzh** [comment]
I think I found two problems. I tried fixing them, but failed hilariously since your code is a bit over my head. 
1. The order statistic computation is, in your notation, nCi x^i (1-x)^(n - i). You appear to have set i = n-1, which is fine, but even then it is not equivalent to (n - (n-1)*x) \* x^(n-1).
2. For computing the upper bound, note that you don't just use the n-1 order statistic - you use all order statistics (from 1 to n, I believe), and take the minimum over all combinations of order statistics and n. See slide 14 of the Lecture 7. 

Let me know if this helps! Sorry I couldn't just fix the code - I pushed an attempt, but it wouldn't run...

**Comment by dhzh** [comment]
Sorry I mean sum from i=j to n, nCi x^i (1-x)^(n - i). See page 15 of this handout: http://www.econ.umn.edu/~bajari/iosp07/Lecture8.pdf

**Comment by dhzh** [comment]
Actually forget about all that - now I see we only observe data for the n-1 order statistic. And your formula is correct.

Ugh. Sorry. It takes me a while to catch up.

**Comment by dhzh** [comment]
Aha I think I got it!

For the lower bound, bid+increment > valuation of the n-2 person, not n-1! This is because, in a second price auction, the n-1 person wins, but it's possible that the n-2 person has a higher valuation due to discrete bid increments. It's not possible, however, for the n-2 person to have a higher valuation of bid+increment, since then he/she would have just bid that and won the auction.

Theorem 2 on page 10 of CH also says this, except they applied it to first price auctions. They had terrible notation, though.

The bounds are now work (pushed). 

One remaining issue is that the bounds still overlap at the very edges - not sure what to do about that/if we should apply some sort of non-parametric smoothing.

**Comment by dhzh** [comment]
Ugh I think that may be wrong too. Let me email DongJae

**Comment by poliquin** [comment]
I like the idea regarding person `n-2` not having a value higher than bid + increment.  It's OK for the bounds to overlap; Haile & Tamer say the bounds can even cross in finite samples.  They suggest smoothing to handle this, but it looks like too much work.  I'm OK with bounds looking funny in places, especially near the edges of the support.

Let's see what DongJae says, then I'll double check the formulas and everything.

I'm making progress on 1(3) now.  Hopefully pushing something tonight.
